<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title>The Things Gateway</title>
<link rel="stylesheet" href="style.css" />
<script src="script.js"></script>
</head>
<body>
<header>
<img src="images/logo.svg" alt="The Things Network" width="200" />
<h1>The Things Kickstarter Gateway</h1>
<div class="details">
<strong>Hardware</strong> <span id="hwversion"></span> <br />
<strong>Bootloader</strong> <span id="blversion"></span> <br />
<strong>Firmware</strong> <span id="fwversion"></span> <br />
</div>
<div class="links">
<a class="button" href="/index.html">Settings</a>
<a class="button" href="/info.html">Info</a>
</div>
</header>
